### ISSUE TITLE
Runtime ClassLoading by Jclass*

### ISSUE THREAD

**Issue by dz333** [polyglot-compiler/JLang#35]
There are cases when the runtime is passed a pointer to a Class object (i.e. a `jclass*`).

However, if this dereferences to NULL (meaning the class has not yet been loaded), there is no way for the runtime to call this class's class loader function.

We need to add this information into a struct (so it becomes a `struct*` instead of a `jclass*`) which would look like: `{ func* class_loader, jclass* clazz}`

**Comment by guoyiteng** [comment]
Fixed in PR #42. We parsed the name of types needed to be loaded based on their signatures in `JavaMethodInfo`/`JavaFieldInfo`, so that we could directly look up their loading functions and invoke them in runtime.

**Comment by guoyiteng** [comment]
You can close this issue after you review PR #42.
