### ISSUE TITLE
native/threads.h:3:10: fatal error: 'functional' file not found

### ISSUE THREAD

**Issue by knight2015** [polyglot-compiler/JLang#63]
native/threads.h:3:10: fatal error: 'functional' file not found while building runtime.

environment：
1. Ubuntu 14.04 in docker
2. llvm+clang 5.0.1
3. ant-1.9.4
![test2](https://user-images.githubusercontent.com/14366358/78656087-7696b700-78f9-11ea-8b2e-69b640e2dea7.png)

**Comment by dz333** [comment]
It seems your system doesn't have the C++ standard library installed or Clang can't find it for some reason.
[This thread ](https://askubuntu.com/questions/516801/clang-fails-to-compile-simple-hello-world-c-program) might help you debug this.

**Comment by knight2015** [comment]
Thanks, this issue is resolved after I install libstdc++-7-dev
