### ISSUE TITLE
java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by jsomeara** [polyglot-compiler/JLang#76]
Not exactly sure what to say here, but this is the issue I'm getting:

"java -version" outputs 1.8.0... should it be java 7?

JDK7 and JAVA_HOME are both set to JDK 7

![image](https://user-images.githubusercontent.com/80555253/129100293-c9feb374-216f-489e-be56-8264c517a989.png)

**Comment by dzagieboylo** [comment]
Hi,

Your JAVA_HOME variable should be set to your java 8 install location, not java 7 ([see the quick start guide](https://github.com/polyglot-compiler/JLang#quick-start-guide)) If this doesn't solve the problem, let me know.

**Comment by jsomeara** [comment]
I will try that, the quick start guide says in the JDK 7 section: 

> When trying to run programs compiled with JLang you will need to set the JAVA_HOME environment variable to this value as well

was confused by this I guess.

**Comment by dzagieboylo** [comment]
Yeah its confusing - it would be nice if JLang didn't need a bunch of different JVM versions for different components :shrug:

**Comment by jsomeara** [comment]
Working great now! Thanks so much 👍
