### ISSUE TITLE
 Class "org.apache.sshd.common.Channel" clashes with package of the same name

### ISSUE THREAD

**Issue by ljcppp** [polyglot-compiler/JLang#77]
When I use JLang to compile "org/apache/sshd/SshClient.java" (one module of Apache SSHD) to LLVM IR, I met this error.
But when I check this folder, I can't find the same name package.The only similar package is "org.apache.sshd.common.channel",which is not same as the "org.apache.sshd.common.Channel" Class. I wanna know if JLang is case insensitive or there are truly something wrong in it. 

The command I use is `jlangc -sourcepath org/ -d out -entry-point org.apache.sshd org/apache/sshd/SshClient.java` in the "yourPathToApacheSSHD/mina-sshd-sshd-0.14.0/sshd-core/src/main/java" folder.

**Comment by andrewcmyers** [comment]
What OS are you using?

**Comment by ljcppp** [comment]
wsl2 ubuntu 18.04

**Comment by ljcppp** [comment]
> What OS are you using?

wsl2 ubuntu 18.04

**Comment by ljcppp** [comment]
I solved this problem by using Vmare virtual mechine. Thank you.
